# Generated by Django 5.2.4 on 2025-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='phone_no',
            field=models.IntegerField(default='00000000000', unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
