# Generated by Django 5.2.4 on 2025-10-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='bill_detail',
        ),
    ]
