# Generated by Django 5.2.4 on 2025-10-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_bill_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='Bill_detail',
        ),
    ]
