# Generated by Django 5.2.4 on 2025-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patients_phone_no_alter_patients_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='status',
            new_name='amount_status',
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.IntegerField(default='12000'),
        ),
        migrations.AlterField(
            model_name='apointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_no',
            field=models.IntegerField(unique=True),
        ),
    ]
